/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'auth.signup': ApiRouteHandler<{ email: string; password: string }, ApiResponse<201, { accessToken: string; refreshToken: string }> | ApiResponse<209, { error: string }> | ApiResponse<401, { error: string }> | ApiResponse<409, { error: string }> | ApiResponse<500, { error: string }>, never>
    'auth.signout': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'auth.signin': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { accessToken: string; refreshToken: string }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'auth.refresh-token': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'auth.me': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { user: { id: string; email: string; username: string; avatar: string; password: string; createdAt: string; updatedAt: string } }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
  }
    
}