/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'event.generate.form.questions': EventHandler<never, never>
    'api.novel.update': ApiRouteHandler<{ title: string; plot: string }, ApiResponse<200, { title: string; plot: string; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'api.novel.get': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { title: string; plot: string; coverPrompt: string; chapters: Array<{ _id: string; title: string; content: string; novelId: string; chapterPrompt: string; chapterNumber: number; isPrologue: boolean; isEpilogue: boolean; contentSummary: string }>; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'api.all.novel.get': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { novels: Array<{ _id: string; title: string; plot: string; coverPrompt: string; chapters: Array<{ _id: string; title: string; content: string; novelId: string; chapterPrompt: string; chapterNumber: number; isPrologue: boolean; isEpilogue: boolean; contentSummary: string }> }>; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'api.novel.delete': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { title: string; plot: string; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'api.novel.create': ApiRouteHandler<{ title: string; plot: string }, ApiResponse<200, { title: string; plot: string; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, { topic: 'generate.form.questions'; data: never }>
    'api.form.update': ApiRouteHandler<{ fields: Array<{ label: string; level: number; _id: string; answer: string; isAnswered: boolean }> }, ApiResponse<200, { success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<404, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'api.form.get': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { level: number; question: string; answer: string; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<404, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'api.chapter.update': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { title: string; plot: string; coverPrompt: string; chapters: Array<{ _id: string; title: string; content: string; novelId: string; chapterPrompt: string; chapterNumber: number; isPrologue: boolean; isEpilogue: boolean; contentSummary: string }>; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'api.chapter.get': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { title: string; plot: string; coverPrompt: string; chapters: Array<{ _id: string; title: string; content: string; novelId: string; chapterPrompt: string; chapterNumber: number; isPrologue: boolean; isEpilogue: boolean; contentSummary: string }>; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'api.chapter.create': ApiRouteHandler<{ title: string; chapterPrompt: string; chapterNumber: number; isPrologue: boolean; isEpilogue: boolean }, ApiResponse<201, { title: string; chapterPrompt: string; chapterNumber: number; isPrologue: boolean; isEpilogue: boolean; success: boolean }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<401, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'auth.signup': ApiRouteHandler<{ email: string; password: string }, ApiResponse<201, { accessToken: string; refreshToken: string }> | ApiResponse<401, { error: string }> | ApiResponse<409, { error: string }> | ApiResponse<500, { error: string }>, never>
    'auth.signout': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'auth.signin': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { accessToken: string; refreshToken: string }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'auth.refresh-token': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'auth.me': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { user: { id: string; email: string; username: string; avatar: string; password: string; createdAt: string; updatedAt: string } }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
  }
    
}